config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
    get 'pages/about' => 'pages#about'
    get 'pages/thanks' => 'pages#thanks', as: :thanks
    resources :signups

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/signup.rb
class Signup < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

	def about
	end

	def thanks
	end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController

def new
@signup = Signup.new
end

def create
@signup = Signup.new(signup_params)

@signup.save
redirect_to :thanks
end


private
 def signup_params
  params.require(:signup).permit(:firstname, :email)
 end













end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stories</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300" rel="stylesheet">

  <style>
    
  	body	{
  		font-family: 'Slabo 27px', serif;
  	}
  </style>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
<link type="text/css" rel="stylesheet" href="style.css">


<meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple Menu - Sidr Example</title>
    <!-- Include Sidr bundled CSS theme -->
    <link rel="stylesheet" href="../dist/stylesheets/jquery.sidr.dark.css">
    <!-- Your CSS -->
    <link rel="stylesheet" href="style.css">
    <script type="text/javascript" src="/assets/javascripts/jquery.sidr.js"></script>
    <script type="text/javascript" src="/assets/javascripts/newapplication.js"></script>
    <script type="text/javascript" src="/assets/javascripts/application.js"></script>

</head>
<body>
        
<div class="aboutpic">
    <br>
    <br>
    <%= image_tag("whitemenuicon.jpg", id: "simple-menu")%>


<div id="sidr">
      <ul>
          <li><%= link_to 'Home', "/"%> <img alt="close" class="icon-close" src = " <%= image_url('close-white.svg') %> " width="24px"></li>
          <li><a href="#">About</a></li>
          <li><%= link_to 'Contact', controller: 'signups', action: 'new' %></li>
      </ul>
          
</div>
    <br>
    <br>
    <br>
    <br>
    <h1 class="aboutheading"> Relive your favorite memories </h1>
  
    

</div>

<br>
<br>
	
  <div class="aboutsupportingsec">
    <h2 class="aboutsubhline"> No more sorting through photos </h2>
    <h4 class="aboutsubtline"> Stories automatically finds your best photos and creates a new travelogue. This way you can capture and share your special moments in fresh new ways.</h4>
    <br>
    <br>
    <br>

    <div class="aboutbtnbot">
       <p> <%= link_to 'Sign Up', controller: 'signups', action: 'new' %> </p>
    </div>
    <br>
    <br>
    <br>
  </div>


  
</body>

</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
<link type="text/css" rel="stylesheet" href="style.css">


<meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple Menu - Sidr Example</title>
    <!-- Include Sidr bundled CSS theme -->
    <link rel="stylesheet" href="../dist/stylesheets/jquery.sidr.dark.css">
    <!-- Your CSS -->
    <link rel="stylesheet" href="style.css">
    <script type="text/javascript" src="/assets/javascripts/jquery.sidr.js"></script>
    <script type="text/javascript" src="/assets/javascripts/newapplication.js"></script>
    <script type="text/javascript" src="/assets/javascripts/application.js"></script>

</head>
<body>
        
<div class="mainpic">
    <br>
    <br>
   <%= image_tag("whitemenuicon.jpg", id: "simple-menu")%>


<div id="sidr">
      <ul>
          <li><a href="#">Home</a><img alt="close" class="icon-close" src = " <%= image_url('close-white.svg') %> " width="24px"></li>
          <li><%= link_to 'About', "pages/about"%></li>
          <li><%= link_to 'Contact', "signups/new"%></li>
      </ul>          
</div>
    <br>
    <br>
    <br>
    <br>
    <h1 class="heading"> Create and Share Stories </h1>
  
    <div class="btn">
       <p> <%= link_to 'Learn More', "pages/about", :style=>'color: white;'%> </p>
    </div>

</div>

<br>
<br>
<br>
<br>	
  <div class="supportingsec">
    <h2 class="subhline"> Relive and share your adventures </h2>
    <p class="subtline"> Stories automatically creates a digital journal filled with only your best photos. </p>
  </div>
 <br>
 <br>

  <div class="secondarysec">
    
  </div>


  <div class="discoversec">
    <h2 class="subhlinedis"> Discover Stories</h2>
    <div class="btnbot">
       <p> <%= link_to 'Learn More', "pages/about", :style=>'color: white;'%> </p>
    </div>
  </div>

  <div class="footer">

  </div>
</body>

</html>

app/views/pages/thanks.html.erb
<!DOCTYPE html>
<html>
<head>
<link type="text/css" rel="stylesheet" href="style.css">


<meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple Menu - Sidr Example</title>
    <!-- Include Sidr bundled CSS theme -->
    <link rel="stylesheet" href="../dist/stylesheets/jquery.sidr.dark.css">
    <!-- Your CSS -->
    <link rel="stylesheet" href="style.css">
    <script type="text/javascript" src="/assets/javascripts/jquery.sidr.js"></script>
    <script type="text/javascript" src="/assets/javascripts/newapplication.js"></script>
    <script type="text/javascript" src="/assets/javascripts/application.js"></script>

</head>
<body>
        
<div class="contactpagepic">
    <br>
    <br>
    <%= image_tag("whitemenuicon.jpg", id: "simple-menu")%>


<div id="sidr">
      <ul>
          <li><%= link_to 'Home', "/"%> <img alt="close" class="icon-close" src = " <%= image_url('close-white.svg') %> " width="24px"></li>
          <li><%= link_to 'About', controller: 'pages', action: 'about' %></li>
          <li><%= link_to 'Contact', controller: 'signups', action: 'new' %></li>
      </ul>          
</div>
    <br>
    <br>
    <br>
    <br>
    <h1 class="contactheading"> Thanks. We'll be in touch </h1>

</div>

<br>
<br>
	
  
</body>

</html>

app/views/signups/new.html.erb
<!DOCTYPE html>
<html>
<head>
<link type="text/css" rel="stylesheet" href="style.css">


<meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple Menu - Sidr Example</title>
    <!-- Include Sidr bundled CSS theme -->
    <link rel="stylesheet" href="../dist/stylesheets/jquery.sidr.dark.css">
    <!-- Your CSS -->
    <link rel="stylesheet" href="style.css">
    <script type="text/javascript" src="/assets/javascripts/jquery.sidr.js"></script>
    <script type="text/javascript" src="/assets/javascripts/newapplication.js"></script>
    <script type="text/javascript" src="/assets/javascripts/application.js"></script>

</head>
<body>
        
<div class="contactpagepic">
    <br>
    <br>
    <%= image_tag("whitemenuicon.jpg", id: "simple-menu")%>


<div id="sidr">
      <ul>
          <li><%= link_to 'Home', "/"%>  <img alt="close" class="icon-close" src = " <%= image_url('close-white.svg') %> " width="24px"></li>
          <li><%= link_to 'About', controller: 'pages', action: 'about' %></li>
          <li><a href="#">Contact</a></li>
      </ul>          
</div>
    <br>
    <br>
    <br>
    <br>
    <h1 class="contactheading"> Get the latest update from Stories </h1>

<div class="wtf">
    <%= form_for :signup, url: signups_path do |f| %>
  <p>
    <%= f.label :first_name, class: "labels" %><br>
    <%= f.text_field :firstname, class: "field" %>
  </p>
 
  <p>
    <%= f.label :email, class: "labels" %><br>
    <%= f.text_field :email, class: "field" %>
  </p>
 
  <p>
    <%= f.submit "Join", class: "joinbtn"%>
  </p>
<% end %>
</div>

</div>

</body>

</html>